### ISSUE TITLE
 Style error in the contact form text

### ISSUE THREAD

**Issue by astro-monkey** [wiliamvj/Portfolio#3]
Hello,

I found this bug, `textarea` is not taking text formatting.

The text is also very glued to the top of the border

![bug](https://user-images.githubusercontent.com/63807201/79495441-f956fa80-7ffa-11ea-9de7-36365f5ee096.png)

**Comment by wiliamvj** [comment]
Hi,
Thanks for your feedback, I will look for the error and fix it.
