### ISSUE TITLE
Como hospedar esse projeto

### ISSUE THREAD

**Issue by pedrodepaulaa** [wiliamvj/Portfolio#6]
Onde posso hospedar o site?

Sou novo em programação, não sei como poderia fazer isso

**Comment by wiliamvj** [comment]
Opa,

Você pode estar usando gratuitamente o Netlify ou a Vercel, ambos são simples de fazer o deploy. Basta deixar no seu Github o projeto público, que eles fazem o resto.

Segue um vídeo simples explicando como fazer o deploy usando o Netlify.

https://youtu.be/uMBorVg5Oa0
